<?php
session_start(); // Start the session

include('../LOGIN&SIGNUP/dbconfig.php');  // Include database configuration

$userLoggedIn = isset($_SESSION['email']); // Check if the user is logged in
$username = $userLoggedIn ? $_SESSION['username'] : 'Guest';
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Barangay Dashboard</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link rel="stylesheet" href="Admin.css">
    <link rel="stylesheet" href="pending-approval.css">
    <link rel="stylesheet" href="registered.css">
    <link rel="stylesheet" href="Account.css">
    <link rel="shortcut icon" type="x-icon" href="../HOMEPAGE/logo.png">
    <style>
        /* Apply subtle blur */
        .blur-overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(255, 255, 255, 0.7);
            backdrop-filter: blur(2px);
            z-index: 10;
            display: none;
        }
    </style>
</head>
<body>
    <?php if (!$userLoggedIn): ?>
        <!-- Overlay for guests -->
        <div class="blur-overlay"></div>
    <?php endif; ?>

    <div class="navbar">
        <div class="logo">
            <img src="icon.png" alt="Barangay Logo" class="logo-img">
            <div class="logo-text">
                <h1>Barangay Kalawaan</h1>
                <p>Pasig City, Philippines</p>
            </div>
        </div>
        <?php if ($userLoggedIn): ?>
        <div class="user-info">
            <span>Welcome, ADMIN!</span>
        </div>
        <?php endif; ?>
    </div>

    <div class="container">
        <div class="sidebar">
            <!-- Sidebar will be dynamically generated by JavaScript -->
        </div>

        <div class="main-content">
            <div class="header">
                <h2>Dashboard</h2>
                <div class="chart-container" id="chartContainer">
                    <h3>Activity Overview</h3>
                    <canvas id="barChart"></canvas>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        const userLoggedIn = <?php echo json_encode($userLoggedIn); ?>;

        if (!userLoggedIn) {
            // Show the blur overlay
            document.querySelector('.blur-overlay').style.display = 'block';

            // SweetAlert for login prompt
            Swal.fire({
                title: 'Access Denied',
                text: 'Please log in first to access the dashboard.',
                icon: 'warning',
                confirmButtonText: 'Go to Login',
                allowOutsideClick: false, // Prevent closing the alert by clicking outside
                backdrop: false // Remove default SweetAlert blur
            }).then(() => {
                window.location.href = '../ADMIN LOGIN AND SIGN UP/adminLogin.php'; // Redirect to the login page
            });
        }
    </script>
    <script src="admin.js"></script>

</body>
</html>
